"use strict";
// *********************************************************************************************
// This file is manually-edited by diffing against an autogenerated file. See README.md.
// *********************************************************************************************
Object.defineProperty(exports, "__esModule", { value: true });
